---
collections:
  - name: community.general
    version: 8.6.3
  - name: community.sops
    version: 1.6.7
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.12.0
roles:
  - src: xanmanning.k3s
    version: v3.4.4
    # version: v3.3.1
