---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-server-config
  namespace: puppet
  labels:
    app.kubernetes.io/name: &name puppet-server
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-block
