---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kalooma-v1-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
