---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-config
  namespace: home
  labels:
    app.kubernetes.io/name: &name homebridge
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data
  namespace: home
  labels:
    app.kubernetes.io/name: &name homebridge
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
