---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config
  namespace: default
spec:
  hostPath:
    path: "/var/www"
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: ceph-block
