---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 13.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    image:
      registry: docker.io
      repository: bitnami/nginx
      tag: 1.23.1-debian-11-r0
    pullPolicy: IfNotPresent
    debug: false
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate: {}
    serverBlock: |-
      server {
        listen 8080;
        server_name www.toodlepip.com.au toodlepip.com.au;
        return 301 $scheme://www.etsy.com/au/shop/ToodlepipdesignsAU;
      }

#   extraVolumes:
#     - name: nginx-docs
#       persistentVolumeClaim:
#         claimName: nginx-docs

#   extraVolumeMounts:
#     - mountPath: /var/www
#       name: nginx-docs

    ingress:
      hostname: "/*"
      extraHosts:
        - name: toodlepip.com.au
          path: /
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: toodlepip.com.au
            paths:
              - path: /
                pathType: Prefix
          - host: www.toodlepip.com.au
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - toodlepip.com.au
              - www.toodlepip.com.au
            secretName: nginx

    persistence:
      data:
        enabled: false
        existingClaim: nginx-config

    service:
      ports:
        http: 8080
      type: ClusterIP
      main:
        ports:
          http:
            port: 8080

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        cpu: 15m
        memory: 79M
