---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 13.2.21
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    image:
      registry: docker.io
      repository: bitnami/nginx
      tag: 1.23.3-debian-11-r0
    pullPolicy: IfNotPresent
    debug: false
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate: {}
    serverBlock: |-
      server {
        listen 8080;
        server_name www.bandcamp.tv bandcamp.tv;
        return 301 $scheme://albatrossflavour.com;
      }

      server {
        listen 8080;
        server_name www.toodlepip.com.au toodlepip.com.au;
        return 301 $scheme://www.etsy.com/au/shop/ToodlepipdesignsAU;
      }

      server {
        listen 8080;
        server_name www.kalooma.org kalooma.org;
        return 301 $scheme://youtube.com/pdlfeggs;
      }

#   extraVolumes:
#     - name: nginx-docs
#       persistentVolumeClaim:
#         claimName: nginx-docs

#   extraVolumeMounts:
#     - mountPath: /var/www
#       name: nginx-docs

    ingress:
      hostname: "/*"
      extraHosts:
        - name: www.kalooma.org
          path: /
        - name: kalooma.org
          path: /
        - name: toodlepip.com.au
          path: /
        - name: banddcamp.tv
          path: /
        - name: www.banddcamp.tv
          path: /
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: www.kalooma.org
            paths:
              - path: /
                pathType: Prefix
          - host: www.kalooma.org
            paths:
              - path: /
                pathType: Prefix
          - host: kalooma.org
            paths:
              - path: /
                pathType: Prefix
          - host: www.kalooma.org
            paths:
              - path: /
                pathType: Prefix
          - host: www.bandcamp.tv
            paths:
              - path: /
                pathType: Prefix
          - host: bandcamp.tv
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - kalooma.org
              - www.kalooma.org
              - toodlepip.com.au
              - www.toodlepip.com.au
              - bandcamp.tv
              - www.bandcamp.tv
            secretName: nginx

    persistence:
      data:
        enabled: false
        existingClaim: nginx-config

    service:
      ports:
        http: &port 8080
      type: ClusterIP
      main:
        ports:
          http:
            port: *port

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        cpu: 15m
        memory: 79M
