---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 15.14.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    image:
      registry: docker.io
      repository: bitnami/nginx
      tag: 1.25.4-debian-11-r0
    pullPolicy: IfNotPresent
    debug: false
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate: {}
    serverBlock: |-
      server {
        listen 8080;
        server_name www.bandcamp.tv bandcamp.tv;
        return 301 $scheme://albatrossflavour.com;
      }

      server {
        listen 8080;
        server_name www.toodlepip.com.au toodlepip.com.au;
        return 301 $scheme://www.etsy.com/au/shop/ToodlepipdesignsAU;
      }

      server {
        listen 8080;
        server_name www.kalooma.org kalooma.org;
        return 301 $scheme://youtube.com/pdlfeggs;
      }

      server {
        listen 8080;
        server_name puppet.lab.albatrossflavour.com;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass https://192.168.7.10;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }

      server {
        listen 8080;
        server_name cd4pe.lab.albatrossflavour.com;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass https://192.168.7.11;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }


      server {
        listen 8080;
        server_name scm.lab.albatrossflavour.com;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass https://192.168.2.12;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
      }

#   extraVolumes:
#     - name: nginx-docs
#       persistentVolumeClaim:
#         claimName: nginx-docs

#   extraVolumeMounts:
#     - mountPath: /var/www
#       name: nginx-docs

    ingress:
      hostname: "/*"
      extraHosts:
        - name: www.kalooma.org
          path: /
        - name: kalooma.org
          path: /
        - name: toodlepip.com.au
          path: /
        - name: banddcamp.tv
          path: /
        - name: www.banddcamp.tv
          path: /
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: www.kalooma.org
            paths:
              - path: /
                pathType: Prefix
          - host: www.kalooma.org
            paths:
              - path: /
                pathType: Prefix
          - host: toodlepip.com.au
            paths:
              - path: /
                pathType: Prefix
          - host: www.toodlepipe.com.au
            paths:
              - path: /
                pathType: Prefix
          - host: www.bandcamp.tv
            paths:
              - path: /
                pathType: Prefix
          - host: bandcamp.tv
            paths:
              - path: /
                pathType: Prefix
          - host: puppet.lab.albatrossflavour.com
            paths:
              - path: /
                pathType: Prefix
          - host: cd4pe.lab.albatrossflavour.com
            paths:
              - path: /
                pathType: Prefix
          - host: comply.lab.albatrossflavour.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - kalooma.org
              - www.kalooma.org
              - toodlepip.com.au
              - www.toodlepip.com.au
              - bandcamp.tv
              - www.bandcamp.tv
              - puppet.lab.albatrossflavour.com
              - cd4pe.lab.albatrossflavour.com
              - comply.lab.albatrossflavour.com
            secretName: nginx

    persistence:
      data:
        enabled: false
        existingClaim: nginx-config

    service:
      ports:
        http: &port 8080
      type: ClusterIP
      main:
        ports:
          http:
            port: *port

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        cpu: 15m
        memory: 79M
