---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-php
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-php
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    image:
      repository: ghcr.io/truxnell/container-images/nginx-php
      tag: v1.0.0

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television"
          external-dns/is-public: "false"
        hosts:
          - host: toodlepip.com.au
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - toodlepip.com.au
            secretName: nginx

    persistence:
      data:
        enabled: true
        existingClaim: nginx-php-config

    service:
      main:
        ports:
          http:
            port: 80
            targetPort: 8080

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        cpu: 15m
        memory: 79M
