---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - emberstack.yaml
  - external-dns.yaml
  - hajimari.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - k8s-at-home.yaml
  - k8s-gateway.yaml
  - metallb.yaml
  - metrics-server.yaml
  - stakater.yaml
  - weaveworks-kured.yaml
  - rook-ceph.yaml
  - mojo2600.yaml
  - prometheus-community-charts.yaml
  - grafana-charts.yaml
  - vmware-tanzu.yaml
  - minecraft-server-charts.yaml
  - oauth2-proxy.yaml
  - kubernetes-dashboard.yaml
  - albatrossflavour.yaml
  - bjw-s.yaml
  - descheduler.yaml
