---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-config-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name node-red
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
