# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: velero-helm-values
    namespace: default
data:
    cloud: ENC[AES256_GCM,data:nlnI5AXHdnJmRgqKHFx0S5/HttBdrJyvMYvwRDvEf/aXVzT+XkYklEctQP9q2mu8684tsGF7zA2Gv4DrQZUhLlMPMQx7uQyOoe9DcIv9DDwpAnvbmzX0p4iTIdrFopQB+jOPanlioOc=,iv:QsJeP8v2vvBNYfMSQfVXkoJ0KSCFsx5Dsq1rBYxOboM=,tag:Rv1ygRMzyMi9BamTHI7ciw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUStMenoyWllmdldvRDNG
            dWJwd2NrLzBjWVF5SDRTL3RoY0FhZlhOUERrClF4RjZhQlgvMFQrUFVnV1hHNEgv
            MGdWRU5iWjFDbFhFVmFjaEx5VHd3OGMKLS0tIFVROWZ6WDB4Mlh0R1JhSXg5N2dO
            TDEvaG13TUJpN0RiNS9hQUM5YmF5Y0kKB5c8J5wfWeZtxNhOhdqmXu9uIL7QMZT6
            r1gl9ACLmTSzn9G02eLwCzYRtlFbmGw/scQ6Uvj9EWFG9vGv/23KCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-16T03:03:29Z"
    mac: ENC[AES256_GCM,data:/p5mYIobwfnVWABCH0dItWbpEBLLGKTYnwNzsOtr8g8ZC5U0rKNadqJoApL5RAvTbQ8CkWBAMQXlL4EJsdX+vfWhnS2Y9EDXTRKf6hdZqxXb+RpqL8joHa4UFPXxeIaNzicZGqubbEZVzVjniDcbdfkuOZhQrQAiHC9b8L6UquE=,iv:g6zuDaEndHHfSYZVVG8ipy5akt79mR5PKWJTsQeKpkc=,tag:K3bxxnwazrXyusaUGZ7xbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
