---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.18

    env:
      TZ: "${TZ}"

    auth:
      enabled: true

    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_MOSQUITTO_ADDR}"
        externalTrafficPolicy: Local
        port: 1883
        protocol: TCP
        targetport: 1883

#   ingress:
#     main:
#       enabled: true
#       ingressClassName: "nginx"
#       annotations:
#         nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#         cert-manager.io/cluster-issuer: "letsencrypt-staging"
#         external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
#         external-dns/is-public: "true"
#         hajimari.io/enable: "true"
#         hajimari.io/icon: "television"
#         hajimari.io/group: "Media"
#       hosts:
#         - host: &host "{{ .Release.Name }}.lab.${SECRET_DOMAIN}"
#           paths:
#             - path: /
#               pathType: Prefix
#       tls:
#         - hosts:
#             - *host

    persistence:
      configinc:
        enabled: true
        existingClaim: mosquitto-config
      data:
        enabled: true
        existingClaim: mosquitto-data

    podAnnotations:
      backup.velero.io/backup-volumes: 'configinc,data'
#       - configinc
#       - data

    resources:
      requests:
        cpu: 15m
        memory: 64M
