---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owntracks-config
  namespace: home
  labels:
    app.kubernetes.io/name: &name owntracks
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
