---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kapowarr-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name kapowarr
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
