---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-long-term
  resources:
    requests:
      storage: 1G
      # persistentVolumeReclaimPolicy: Retain
