---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-long-term
  resources:
    requests:
      storage: 1G
  volumeName: pvc-01e7cc39-3b57-4e78-abb9-b1ec2858e1fb
