---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app pihole
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.9.1
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    image:
      repository: pihole/pihole
      tag: "2022.07"
    serviceWeb:
      loadBalancerIP: "192.168.2.250"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: "192.168.2.250"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-data
    adminPassword: "admin"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "dns"
        hajimari.io/group: "Cluster Ops"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
      path: /
      hosts:
        - &host "pihole-k3s.lab.${SECRET_DOMAIN}"
      tls:
        - secretName: *app
          hosts:
            - *host
      resources:
        requests:
          cpu: 5m
          memory: 125Mi
        limits:
          memory: 250Mi
    dnsmasq:
      upstreamServers: []
      customDnsEntries: []
      additionalHostsEntries: []
      staticDhcpEntries: []
      customSettings: []
      customCnameEntries: []

    adlists:
      - https://hosts-file.net/grm.txt
      - https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/porn.txt

    whitelist:
      - clients4.google.com

    blacklist: {}
    doh:
      enabled: true
      name: "cloudflared"
      repository: "crazymax/cloudflared"
      tag: "2021.5.7"
    serviceDhcp:
      enabled: false
    monitoring:
      podMonitor:
        enabled: true
      sidecar:
        enabled: true
        image:
          pullPolicy: "IfNotPresent"
          repository: "ekofr/pihole-exporter"
          tag: "v0.3.0"
          port: 9617
        resources:
          limits:
            memory: "128Mi"
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 8.8.8.8
