---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes
      chart: pihole
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 5m
  values:
    serviceDhcp:
      enabled: false
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.1.250
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceWeb:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.1.250
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    virtualHost: "pihole.${SECRET_DOMAIN}"
    persistentVolumeClaim:
      enabled: false
    replicaCount: 1
    adminPassword: "admin"
    DNS1: "8.8.8.8"
    DNS2: "8.8.4.4"

    adlists:
      - https://hosts-file.net/grm.txt
      - https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/porn.txt

    whitelist:
      - clients4.google.com

    blacklist: {}
    regex: {}
    ftl: {}
    webHttp: "80"
    webHttps: "443"
    hostname: ""
    hostNetwork: "false"
    privileged: "false"
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 8.8.8.8
