# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: pihole-helm-values
    namespace: default
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:xkMn9qx+CuTMNSOKnP/Hw8ZshDgOWzMS3kGVjY530mETae5xAfAR+kJP9wU9a2e2LiKWhQ29wcuXalbNDxEK2rJwdteAfIVDH3sNnxj6xRcr23wIeyxVmyb3hm+mYmtVFIeRYC8fdEm3aIpRks8fZAY12tA3p9lzZU/ZfqpE3zo6bJqG1qr8vv9vwelRN8SisUHtwrqr6VDmc1MoBKVYnR8oVTNetrLpPSCkCfHgoV717McEdq6/rdo5aA2DUlNebGJtMsJ8lhcLJITI1OboJfuuYq6dME4akXk4SkYj0mStYTx2ECNrz0S/zGiwL2Q7BxK0RdECCJOtAs1G1NmeRkxjk4rbtXdyXs3rU38j8MX82ZyJvWoYh8KApOpr/B3lojERCAnwgRRDS3r1kYDr0p4FsYD8h8ldZGmDD8/+4GJu3WnP6wnHokx0FUgen7GKfkV02x85tR279QBdLDOuWihDfL5DMoGW7NkOH4kFc1/St3+SNI2zmgIPCrVTPS2jNBaJ/gBAOnSU6yMhyYEVmlRU00wAJxFWEygqBRVBjafS040RFx2fhlybsg5kb5CjATwWW9oUA8eLiEFrcjwLx2HwyPh/xrg8HtxWHKAeqY9050QIuJ09yeKTJspDNyttjXQNIZ2wE3RTYlOHiXNuON39kmAkZr7+i5SyyZsJ7iL/lJH4D14HKzMFZz/ZVPrzW9jrXy5K6xXftQ/4bo6hm+D96e62hJHJNhkioaCXflQXeq3Xc+F/zO8+tIiO8LUOvUxweJmmm/ESiYj05weGVzLPRHSrOTJz+nnawsfcVvVtRkGs/vM876pflAYxDrgUDTuXIsqdfDub2xJN2mrtryzukJ+BGM0Y2gMbn9j0ZTKDjOcoDtUxHoQnnQe2EAedGbfuZ/fHl+HzL30yqmBzyzpJOkBAf9bXcw0o77Nx9YR7OfvQApP6NYGVrmJOiKN/7UFFpLUkJPh+hObjs4PtwX/F2UlX9jrRUEQ3OQZjZ6Z3I5mXmkMbERc6Ogxe7Dm2A/pCW57mrJBXmP7nD9jj+CHapFtNmcPgZjOPsnwSejLnwRn6Ru2e4jNP5sLW3nQUSHSw+fh3JC12U0Zw0IYy/GBD3SuWLh3M477IbdnciGGANlEjmCsiYID9s7IG4wb1N41XL3RRC4WRej2iVXpigCXsAyxARoh3NqbGSeH6zqZ6Mlzm1Z5LE0wcar1AOGkeRxXyJy9dl6CNsq/YV+aXvA3+eA==,iv:/dfC4IQ3syZO6sbkqmseF16fCrl2TsC+NrFFdRGEAys=,tag:fGXwG1aluFETgy3Sl/hcUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaEVrK1FlNHZNZ1Z0Tk5Y
            S1ZGNjJ1MjhJZ0U2NFFsZFlMaWJwRFVrUUdBCjJCZS9hSWthSEVXNHBDOWV0N3hp
            bmtuMStNM1Q5YjlFcGlVQVJLcnNjMFEKLS0tIHJSOEEweGdCTFBTL3ZWcjZrVmNk
            QTVVS3VlbWQxRDc2dVVTVVdQT2owMlEKPOncqCTyKur8A5fmlmwOK9NC9h85sM7S
            6ELPnhikltctVpxc1QsxkdhSKuHcR84eBWU078Vo/QzP3NnTRwCs9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T06:35:31Z"
    mac: ENC[AES256_GCM,data:Ez/3fKQcoKRpgrvwU4biIOIGG7VVr5B8RyCPzb9nofO2GubgcawSgaay6pJvmzE+FE2UbXCsbah5AIgzSE+zvyiz4BCutQHL1zMvTgzsS3uxmniyGQ0l8waJffi48irDgH9y2Jtea8KvSylunZ/gyK5jHkit7c1yftnkxFt9OAI=,iv:kY5SEYuPhEzvYAT74L82MGvxvvTPfxb980MV4zmIt/w=,tag:6QNyMstihf+ShDwXQoqRbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
