# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:w39nnLSacAkMSuGSmFAfbL37iIg=,iv:7NHb7Yn9F+5rlTofjT5an2PjXdibp55AmmZ8DpDAaEI=,tag:waxzqxPsbd7Z+8eso06REg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JLnsHBtM4x8h8IXRB1nF47u4Ht41WMBsPdvz,iv:wHhtLz6JiuUnjtcUJSnUzGdSo7BnHQO+T+mUpiKnEfw=,tag:d9SQLcrEC9LZtpZpvTNwAg==,type:str]
    EMAIL_ADDRESS_1: ENC[AES256_GCM,data:qXePbaO8eSJ1yPgwKJwh2pkBg5rCPrTn85QB,iv:/B09hPmbYtrKKmfkkZnlU9bNi+laqoIJVpjMwPMdpjM=,tag:iQwWL6oECm6+ihU4N6IcgA==,type:str]
    EMAIL_ADDRESS_2: ENC[AES256_GCM,data:SCpF6Z0guYEcGzzE9O2YjsHy,iv:FWSin0eAZnXroz2CJ7t/uHicnzUOlvyJSop9YXl/P70=,tag:kB9Os9MJyQLPYlLnKzYG1Q==,type:str]
    EMAIL_ADDRESS_3: ENC[AES256_GCM,data:qmO01gO9FD/PEtIwBwPgC53iV73regk=,iv:mO28yuxBoBEgJuJOe4kreCu2OZvOqyREK/sMrd4Waj8=,tag:jcMUIP1ZBo/RDnX5tumzaA==,type:str]
    EMAIL_ADDRESS_4: ENC[AES256_GCM,data:YZdmwOxVN9deCP8obfFiGBFiupyX,iv:9Gw8mPzqQK+lvvnW96XS+ItvWcXwM9LOheS4E0S+Sl4=,tag:vj4Ja850EJBP1rl14p/fHQ==,type:str]
    EMAIL_ADDRESS_5: ENC[AES256_GCM,data:8TeqaYJFq2z2lrIV0hpY4H3fqniwdDel,iv:vlfsJNkcqCzLYVWAeH2dEpc11AdtV/oVUKegEatSxBI=,tag:mdLB/yk0g+cVY4GrXz5JSA==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:xAlhZXXUkEjZ+M0cc+XDnl64iGDC5y766KCKLIglTxjx7c/c5usAE2Xoh7EcQjUhaIPA7UapiD3ZxxdzgjfpsBePre96yelQ,iv:ZQRrWYgYbnS92wJvQxr+MlDx6UIsuD7tHsrFNhRf8oQ=,tag:1fa8vHEEzG66bfFeG786cw==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:ny76IX5cI5OoUPBjNG7h937cw9XJ7g/D,iv:164Wluug+ZW/AdJAqNLgJ1I5HdZ12U7La8BecdhPR44=,tag:+jbiFH20EA8hOnWnRIrx0w==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:SehS7oubo3ggWD3iqoYZtinLVl7/ny11JPXcM495Zyw=,iv:1OEqIpBSyWjKZ4Lnekipc1Gvz1T/TnDT4f6X9MxGtSM=,tag:EnAjN51g/azXPelL5N7R/g==,type:str]
    THANOS_S3_ACCESS_KEY: ENC[AES256_GCM,data:+At0XHX9KaZkS+alxboVHQ==,iv:futASTeSDB2Hexn3WuVj+IsFhb7xeRg3mTbimZeoGiY=,tag:gpucxRz2KDJLQf+RwHVAJA==,type:str]
    THANOS_S3_SECRET_KEY: ENC[AES256_GCM,data:gGREFBaLLUx5VVRcDNVWW4VpRNTYZFJxZFkvz/ars1A=,iv:bn2Pru3k7W5TPQJPxOI0Fmbyn0znhgYo+FtCcw/Wtrk=,tag:a3AzCGpvmixsRlM/GcfD+w==,type:str]
    MOSQUITTO_USER: ENC[AES256_GCM,data:/4Mxlsg=,iv:qnf1z4AyTW7mV7BqUJWSdQ/dun0G+DR6CPm4Flb3piE=,tag:LlsFOcuWBrorARwYosGKBA==,type:str]
    MOSQUITTO_PASS: ENC[AES256_GCM,data:ghqfym7rAvo=,iv:8a7p4ReXZsXcxBuHgsy30xqiOAzjPaMfCxYUVUi5KFo=,tag:4XPaNLGpVqecNdwHHQnhCQ==,type:str]
    PIHOLE_PASS: ENC[AES256_GCM,data:xClMrUJdsYQ=,iv:za6lazkxFS1ZXw38kujdhRW4Kn8msNCXwy8RCc0dIuc=,tag:cqeTccCfSxVTwyL5UBRIJA==,type:str]
    SECRET_PUSHOVER_ALERT_MANAGER_APIKEY: ENC[AES256_GCM,data:TIe89ZxCC7rJKxcw9nr7KDZut/AM7uDsjyEG7bXh,iv:f/CdZMhBhrITDH7FZFnX1ym5zpX0DhLIAeiyka/NZWY=,tag:V3lhJlBgxCidxWJtScYlTw==,type:str]
    SECRET_PUSHOVER_USERKEY: ENC[AES256_GCM,data:kmdOOfs5UW07NT10RvE1hhRdk24Es9T8U1H6DUpn,iv:hNpWCv5hBa4l0F7p48ZXwtcuY7RimykH8atIfOUKtiY=,tag:GvUS4LJbZSyudem5pWDffg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR2lsM2V4R3FTL3F6VEht
            c08yNDViTjU3aEpTbys5MkR5VjRkNzg5MW5NCnlhUWRNdTgyNGpSVk82bEZlakYr
            TGJjcExnVHd2Um5aNTFPckhhM3FBZ28KLS0tIHB4ZGtOKzdsTXZuTzRKL3ViUU13
            endhRHdHUVROZWZkZk5BWGt6eU1yS0kK44TEWGV2KpsD9y9kz72KZsWViCfGy2yh
            EDd875HuyM4LM3mLZb0ApzzL7LBDSdp6wsu8gdy1GhiRbq2YKQREfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T03:17:23Z"
    mac: ENC[AES256_GCM,data:rlqRVFeB49dRYd4A8ZdE6HzsWNTOdT8E/7WBHlostyUNWi+pOLriGMpKa60wdm8Nf8nU68DRk1/B+KLLiI8jwij0Z/fC0vPlq8+tJm79Y1V0ihl0kenFTUM+aFjlrXwFONyV+5UDxl6X+FBkSQ+N5a8mD3s8xR8xkRQbmLz78fE=,iv:X6wQMBKqJnR6X9QD1OubNjpZpXneJ2RnHVCT/4OXIZc=,tag:yhj4FXwtqAKoK+Nyp0u1IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
