---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Australia/Sydney
  METALLB_LB_RANGE: 192.168.2.151-192.168.2.250
  METALLB_K8S_GATEWAY_ADDR: 192.168.2.151
  METALLB_INGRESS_ADDR: 192.168.2.152
  SVC_QBITTORRENT_ADDR: 192.168.2.249
