# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Cu/uZnRx+XntMqUTieHMRHbm+w==,iv:KsFFHqB5GwBNEmwYJDm9c8IvD431N1h1hO+y/Wbgg8k=,tag:cvVRgSn4sPYcuMGxCEdjvQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:jHqO3cTEUDLqR8SkzCqOVzwYWZ46DWjSCiqM,iv:tdpAHUhxYes9y2nAvbnLy7r5LJQs04h3r8lPqHblQO4=,tag:2i9YyOCmExp8QBW/G2pwNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucm1ia2VQM3lBNWU0TFN6
            dk96TUYxYi9UdmlJQk4zM0l5TnZTR00xamlNCnpyTHNHTXNiTWNjaWJtQjZrdW9O
            YW9FWFJjRDZpU29ZQUNuRWtZUW5NbUUKLS0tIGd1S3N2RG9iUTNtSThMeWhQTUhQ
            QjVKU0N6T2YyY3hYYS9uMmFlZUFEUm8KyU5DcTTb5fidEF8pYwkbwTxxsTdIW5ok
            i9XHLQUG2ggt06lwecTkKdc0IBOj6h8K6NMqofHAxlUrNFqxUFHFKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-30T11:08:21Z"
    mac: ENC[AES256_GCM,data:QqJoqxAOupMcP4gvM1w7qp/X148GAcZQ/PCMTmDob7PRxnL1EvxcL0lPP4j783Or2qrCjA82g1iM5iGPyrcwStc/JsTGs6U6mRODhpqMwHBgX+TmGATp+hBV4JiokroeLZKcwMmUyopEJc5OfB5jB7gFang7p5TrQ+s5MMvVk+Q=,iv:qQwTpR623mDD9FNAhsjVSzHz1f9sFWTCAXH2k6NH/r0=,tag:2qzgZ9Pw2ufZUIZDJdMxKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
