# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:myYA7oUd68VJQKVNrhO/HOtKbEk=,iv:mwawm5eT+y/bhwtcQW5LUusImtU1oIU+BFHLlr7ODNA=,tag:oiOJPA8DdzIW+/hInAHT8Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:NjPekBFnPNJzZP5ZckBJ6+CIemlRCsLnwBO1,iv:aFTQXG04RJImK9m/fudWcSvyVWTyEfguqJL9xBzcNV8=,tag:Lq22nPpReFxDsGI06qXknw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArR0FwN2RJZjNOMnpVMkRz
            N0NXdDA2OEc0bm5KcHBzNDlMVXFSVU5MTlg0CkE2VEhCNlpMdi91bys1dmdaSDNu
            TzFaQ3Q2TUgyakJvdm1GemRGdFJMekEKLS0tIGplZHRuRmJxMDd3MUNVSWJXdDFi
            NG5JWWZCS1JoWE1KVHIwOGdPZjVKVWsKGG1cDALoPLirijmzO1CgkH6rg1NJ4voI
            bjc3faKy7dBsvMMlmztYmrCLwLFRHG8F6zmzIyM+pDjEZ48EwAYEQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-27T06:00:53Z"
    mac: ENC[AES256_GCM,data:qkx+g5oJ09z+u7XJtCmUi7G47hZ6ny9xczJAmwEtaUiOYkSpksXBZC4uTjNKKva8YvIOzk7ie9N75Sfy+0PWg6Bf8qkVCz+j/MoUyTKNW03/RMD5Bmh1n9gg6d9KqPt/oPLiI/Lio+vmB7/BRNDU+mP6j95epvuRM5dCcLWi9Yw=,iv:t+7mufN0tL6z9NMcAWmUyzd5cJdKgZgJcnVXUvmupfQ=,tag:QTwM8XQZfDNHsoLCJqeWTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
