# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: media
stringData:
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:L+dCoMnWU22g0zvAPSMdLM9nqFAtZ1HBlDzgpJnU,iv:E6s5Ix0U26pAFDs3bXtb+BI7M0qpCimc9xuhln5BKIk=,tag:DGBp+VINiBPjb6Q24Mcpcg==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:QKEYsdXvQ27eeUWfc35KuzHkoMT0XkZrOfSUloeO,iv:40Q3kPEPqJPhZdllMwbRP6vz45VKVXvrO20MNYVpzbE=,tag:trxb7fdUR8v6UfHzKtDVaA==,type:str]
    RADARR__API_KEY: ENC[AES256_GCM,data:xa+ZX0tOiTVNxtqZMRpFtRm1Fr2S6N8TVpYeG/TglyE=,iv:2648GoNkfYjB5f45evTAA1MUfII3j+yefQg+h1+s/Ug=,tag:l+vHi5x+bl+N2Zru5+uApQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YWVvejlGWnNmZWs5SjBw
            OTZHOEVyUm1DV1BmanN0MCttNzh5SmdVUmxNClNiMEZlRE5WVm5ZY00zamNMbXMx
            R1F0NTVqNjc4VWEyZWtNbExDT2lNTEUKLS0tIEJnc0FOT2Y1MWs1NWRxV1AxdnlP
            ajVjUThEVDNwN1dqZ0lJTGt6YU5mSVUK9okMND98K8jEjKRlD1kAItkRtcWwr/iU
            a18V4YwhkyAi6auLRXnuprcP5K0muHY0RUkr7fmFMLlMqTvCXtzYyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-25T10:31:15Z"
    mac: ENC[AES256_GCM,data:Or3ydOJQVi0saAMfUGngTqQ+ve7LkClRYiZ0+TfXIR7MLYzpIESWUu/0iV7f9BH89DeM5NLyN0noxBZxClYWBrFHsqCwxlkXcUwThnQN3aAoKiglHd0Hdd6JfuqQym/Gxqw0C0CSg0D4B/ZJCW+GqBVV2ld/TMIDGmRrCz3+4qw=,iv:ZI2twnkG3oNMfx0//Sw6KB9H2us7DtknhKYVViwL3PU=,tag:NI6O5TYQzva3xiY5KPAh1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
