kind: Secret
ansible_user: ENC[AES256_GCM,data:L2o=,iv:BmYpLOeT0PlgztEsIKbh2B5tQRZCgfMidm9FczLUG2k=,tag:Z5jaJf7i7cuf6N4bCItb5g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ghQwl3w2EO4=,iv:xjvCYFUDdFe2RfOgteUSrYGB9qwrkaSjHynnWmnJKGk=,tag:xyhB+tUYvqcF6vrH1QO6DQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhd1FMRWJBRDdtemFRWWdZ
            V3c4RmdjYXlkV09OTjJvaWtzVUk2K08rNkhBCmpzTzRwRFBJdWorZ2JveDdsVmtv
            dkdJZUdueW9QdXZMNXBEZFBsSk5qam8KLS0tIHZmaEw4MkVNWXVWMTA2alhiUHdE
            UTRhaHF5dnlOamR1dm9hZzE0RlUxWmcKRdBRsKjuOrw63STEFzRhE3iRG+XXZpQ/
            LrgylJt6iWsQ9r+6Oa0ax/DYfbd7wS/fFHBStSj4PYuz6mTGZ+QfTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-27T21:11:58Z"
    mac: ENC[AES256_GCM,data:Rumxzwaa3Q5GvInrl+Y4hSR1TWZsGtHEZDvOPj0F65ZPN8zlID/+Kt7CSrUPv0/bX3ogO5L1oy1KV6X/LCjO2St/GwppZomVGO2xwa80zld/Dur1O2VleOKF2oXpGJ3R2/4WT+mugkuZwiG3ioGMJ2P50jftjIiT7comY7hMWH4=,iv:zeB2IILJL3xdX19my3Wmi3404QPksiVk0kgwZxKipbw=,tag:2o/xp9pK8Db/4ETy8crgZg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
