kind: Secret
ansible_user: ENC[AES256_GCM,data:FJMP+WSx,iv:AkR35GxGIObkdipqBMSfI/9I83tAQhkhg/d90mj8V2I=,tag:y8vHr0fqjFca/kNSrw0GSg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:/WXkSegkaKQ=,iv:F1bZ8dGeu6II6ePx2U/Lb/Q9QPudW/AYv5ftfEPfgik=,tag:yPWYuvoSz0PzEgu+RrlzSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdi9NZDVxYTgzTWorZ0w1
            MWFEZWYraUF4QWdWUm5Yai9tQ243NTdHaEdjCkRzVnJKSkdveWNLd2lJajdXMUxB
            ZHJpWXZHM2NUVTk4ci9YcmdvRlV6Y0kKLS0tIHlvU3BRYVg1MkIvWXg5RTliYmxs
            alhOdjF2WGordHVYdnJ2RDBlMUxpdFEKtiA3GEsewzdeaFaoNmXuAbm0XXkaadwM
            YBTbIfB0hs8qh11xpVWW9Gc0F+jGuzsebGdtjVoWVhSkUqtVo5BfYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-27T21:12:25Z"
    mac: ENC[AES256_GCM,data:hz+4n+1hPTRNzgYR+WZNDRSPd8ExI00KCCC2vs65pPUf0cjVqUCOOP2gaThj9ogHMB3iucNW1RCdw3xBefvWSaji4ITmslf91IrjCNksyIx98ta4J4ZN5cXMIjE1BSMmqLo5pgpX2DJiPFYWhk9OOo1+AuJQB0ZRXYsyzXUN1WY=,iv:j/Ho26fCtCrMFbwsQk48m6lOqf0bgqWCmgbq4hhrN24=,tag:Xd95PpXC6AWjVmAcGOHbCQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
