kind: Secret
ansible_user: ENC[AES256_GCM,data:t/SCblFC,iv:zfxK4Fg/B3B3Ir+wEuAvHF0dcUZXW2IrMpcFdRwhj6g=,tag:HgOM0Gai5SwFTcm7B6fBag==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4lBU3hZket4=,iv:oHHAoKgldPYnghzOrQdXy5nPdX2la2rk9LDFnW7IBX8=,tag:1LjkJ9nBUxA/DOIdduCNWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb2RlTkF2RDhNQ3pvSGd3
            aW9nQjJGMnBJRmV5bi90VDJtU2xpeWRyTzFnCndJUFpETmNxU2QwMlIwSEw5Y2x0
            QlNJaHpVWU80WU5laTNRMmFXcmdzYXMKLS0tIDY4VENoVW1lV0N2UUdXUjFTOU9i
            VDZqcUU1cUgyZG51SVpONEtTL1NTSUEK2GNrI58khf8Nw5UPCIkNCJsma/ccHbLX
            6Rp/GRKID6BAirSr18kJFk/W9tk24grHFqjSwdwVZ99oDbbuohsyHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-31T05:55:51Z"
    mac: ENC[AES256_GCM,data:hCY4MGQrflANa9hUtnzJvLoFKzFkwGdObOPNDTmvHBhMh/Uw+j554ur1uN8B9nNzQvBPvx74aYgICDNzf59Jd8FgJsHeWyKsZ1g2k4kT3XLwiqBTps9GD9LTIGEEbqu9aJJebED6zvLKnqwAI4BgEcjc88qh8s8wiYShFHPkGQA=,iv:zYB0bSUK4OXLXwZd6W+ffILBf5T1izLlgxRw5tpVuss=,tag:fIcIqOC1qWn2jfWN0Tnsyg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
