kind: Secret
ansible_user: ENC[AES256_GCM,data:8bzr3lhz,iv:zDD0M+0S9D4tLMt7qjnFtP52zYY7G7bxG+ALAt5rWvo=,tag:xL81J9A+iLISVpJuLsB0Vw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:M+hbbm5dWMQ=,iv:m6wzcUPdWhh6odyWB3F9QwIGoC4hPXvqwH2NdeflSCw=,tag:FF9T1zv5+xCQckPaBzGoVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2emhSTVlkRHZwQmtFODM2
            ZTJkYnNqTWxCVk5nTEpJd3hPN2dCUWhtNTJFClQzRm5wR0htZ3VkeGM1aGsvU0sx
            SHFIa3Z2aldqRUlCa00wcUtXSndGTTQKLS0tIHVyL3RjaFh4VjlkQngvODBKNWJl
            eE8rMmR1aU5mTTNLdGRNblZvdC8yc0kKkN6NUril3ASFE4s0w9RCOk/UcMeCRjJE
            iuRuhA62+Wpjb2RdpInMbMXHZ+ptUS7a1Kwh6JohqlBkAK5yT0AXow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-31T05:55:51Z"
    mac: ENC[AES256_GCM,data:piKjKexoQjfBFpZt+BalkjAgPjZT7/9/cl8nhKYBh1m0+1sM71+vYWIsEXxwYLTYy3H7bxqFmgwOFW2/M314tj9ARnJhFZCXrgFF8WNzKCKBS6NPGI4QxjuFjt8VcDCX118t1TvPlROkxFaKSp8t32mmc9pLxtGv+k2QpChLTPM=,iv:GjvTAuIKx+QB8FcV9NR2uMabIOI1q1kiaqHoOYACI/0=,tag:K7cAN2QXEFoRPvbPH9VcZg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
