kind: Secret
ansible_user: ENC[AES256_GCM,data:7RCoPLh4,iv:9SJOrevjrD7Gn0gtqBwUoRznP1FMzclF+bY2J2ebGWQ=,tag:SAebN67aycxSHVpBLNXmHQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Crs98bfkjgA=,iv:uSqwo3j1Dea5dIzVQAnG3djPxBh2sFF/qmBPU+doz60=,tag:9ePketILWqDQCl+uqvwofw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMUFudlM5dTBQQm1HOWFQ
            UXZMYTlFenZrT1M2c25Cc1pBeEZQTzBnNXhRCkpKT093eEE0aHp4QmlVcW1ySElY
            eHpKbU10WkJYK2kybVRLNit3NDBWTGcKLS0tIGdJQ2dsS3NBN2ZXMXNSeGN1M2Yw
            K1RtVGFOUXYydHBBS202WnQ2aDFCR00KHlnz5QdxWhzNxHMi9CeYiObpBvLo1hi5
            p0k4PdVFzUa+jQAP2Tu2UxeTioIOVbHEm7OXYSQCoQ35kWicXdxmLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-21T02:43:02Z"
    mac: ENC[AES256_GCM,data:lnXirootheQtiCte0vqhv988Xv02WE6Fm00vK9SesUxpFOiV0r/A+ZFhG86UOKAG6+6eCUlfPz/jMWUyvxh4MKyuM4oJCaB2GooenjVwWrIm/ouPHQjenAM5pNmpjJVfP4LwNG+Rf4L65YWF2L9B/ehRCtjSTo29o41aOP43FOU=,iv:d2h6TDC0b7U3Fvrl9uYhl0ehYABEl2bl3iY20K3P8bI=,tag:MHOg/DXha0SY9yj5XaacJg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
