---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi-poller
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/golift/unifi-poller
      tag: v2.10.0
    env:
      TZ: "${TIMEZONE}"
      UP_UNIFI_DEFAULT_ROLE: "homelab-controller"
      UP_UNIFI_DEFAULT_URL: "https://192.168.1.1"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_USER: "admin"
      UP_UNIFI_DEFAULT_PASS: "H4l18ut666"
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: false
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
      UP_PROMETHEUS_NAMESPACE: "unifipoller"
    metrics:
      enabled: true
      serviceMonitor:
        interval: 2m
        scrapeTimeout: 30s
      prometheusRule:
        enabled: true
