---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app scrypted
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: scrypted
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: koush/scrypted
      tag: v0.2.5
    env:
      TZ: "${TIMEZONE}"
      SCRYPTED_INSECURE_PORT: &port 80
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
          nginx.ingress.kubernetes.io/satisfy: "any"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"

          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
        hosts:
          - host: &host "{{ .Release.Name }}.lab.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: *app
    persistence:
      config:
        enabled: true
        existingClaim: scrypted-config
    podAnnotations:
      backup.velero.io/backup-volumes: config
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 150m
        memory: 750Mi
