---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kalooma
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minecraft
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2022.10.0-java17
    persistence:
      dataDir:
        existingClaim: minecraft-data
        enabled: true
    service:
      minecraft:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${SVC_MINECRAFT_ADDR}"
        ports:
          minecraft:
            enabled: true
            port: 25565
            protocol: TCP
            targetPort: 25565
        externalTrafficPolicy: Local
    resources:
      requests:
        memory: 2Gi
        cpu: 250m
      limits:
        memory: 2Gi
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    extraEnv:
      ENABLE_AUTOPAUSE: FALSE
      #  SPIGET_RESOURCES: ""
      #  MODS: "https://github.com/EssentialsX/Essentials/releases/download/2.19.4/EssentialsX-2.19.4.jar"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: PAPER
      forceReDownload: true
      onlineMode: false
      difficulty: peaceful
      maxTickTime: -1
      serviceType: LoadBalancer
      gameMode: adventure
      motd: "\u00a7feviljungle\u00a7 - \u00a7a\u00a7llobby\u00a7"
      icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-13.png
      rcon:
        enabled: false
