---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 41.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    priorityClassName: high-priority
    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
        receivers:
          - name: "null"
          - name: "pushover"
            pushover_configs:
              - token: "${SECRET_PUSHOVER_ALERT_MANAGER_APIKEY}"
                user_key: "${SECRET_PUSHOVER_USERKEY}"
                send_resolved: true
                html: true
                priority: |-
                  {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
                url_title: View in Alert Manager
                title: |-
                  [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
                message: |-
                  {{- range .Alerts }}
                    {{- if ne .Labels.severity "" }}
                      <b>Severity:</b> <i>{{ .Labels.severity }}</i>
                    {{- else }}
                      <b>Severity:</b> <i>N/A</i>
                    {{- end }}
                    {{- if ne .Annotations.description "" }}
                      <b>Description:</b> <i>{{ .Annotations.description }}</i>
                    {{- else if ne .Annotations.summary "" }}
                      <b>Summary:</b> <i>{{ .Annotations.summary }}</i>
                    {{- else if ne .Annotations.message "" }}
                      <b>Message:</b> <i>{{ .Annotations.message }}</i>
                    {{- else }}
                      <b>Description:</b> <i>N/A</i>
                    {{- end }}
                    {{- if gt (len .Labels.SortedPairs) 0 }}
                      <b>Details:</b>
                      {{- range .Labels.SortedPairs }}
                        • <b>{{ .Name }}:</b> <i>{{ .Value }}</i>
                      {{- end }}
                    {{- end }}
                  {{- end }}
          - name: "nodered"
            webhook_configs:
              - url: "http://node-red.home:1880/power-outage"
                send_resolved: true
        route:
          group_by: ["alertname", "job"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 6h
          receiver: "pushover"
          routes:
            - receiver: "null"
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"
            - receiver: "pushover"
              matchers:
                - severity = "critical"
              continue: true
            - receiver: "nodered"
              matchers:
                - alertname = "UPSOnBattery"
              continue: true
        inhibit_rules:
          - source_matchers:
              - severity = "critical"
            target_matchers:
              - severity = "warning"
            equal: ["alertname", "namespace"]
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "nginx"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - &host "alert-manager.lab.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
            secretName: 'alert-manager'
      alertmanagerSpec:
        replicas: 1
        podAntiAffinity: hard
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "ceph-block"
              resources:
                requests:
                  storage: 1Gi
    kube-state-metrics:
      metricLabelsAllowlist:
        - "persistentvolumeclaims=[*]"
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
    grafana:
      enabled: true
      forceDeployDashboards: true
      sidecar:
        dashboards:
          multicluster:
            etcd:
              enabled: true
    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance
    kubeApiServer:
      enabled: true
    kubeControllerManager:
      enabled: true
      endpoints:
        - 192.168.2.50
        - 192.168.2.51
        - 192.168.2.52
    kubeScheduler:
      enabled: true
      endpoints:
        - 192.168.2.50
        - 192.168.2.51
        - 192.168.2.52
    kubeProxy:
      enabled: true
      endpoints:
        - 192.168.2.50
        - 192.168.2.51
        - 192.168.2.52
    kubeEtcd:
      enabled: true
      endpoints:
        - 192.168.2.50
        - 192.168.2.51
        - 192.168.2.52
      service:
        enabled: true
        port: 2381
        targetPort: 2381
    prometheus:
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "nginx"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - &host "prometheus.lab.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true
      thanosIngress:
        enabled: true
        pathType: Prefix
        ingressClassName: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        hosts:
          - &host "thanos-sidecar.lab.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
            secretName: *host
      prometheusSpec:
        replicas: 1
        priorityClassName: high-priority
        replicaExternalLabelName: __replica__
        externalLabels:
          cluster: k3s-cluster
        # remoteWrite:
        #   - url: http://mimir-distributor.monitoring.svc.cluster.local:8080/api/v1/push
        #     headers:
        #       X-Scope-OrgID: anonymous
        podAntiAffinity: hard
        retentionSize: "100GB"
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        retention: 20d
        enableAdminAPI: true
        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "ceph-block"
              resources:
                requests:
                  storage: 120Gi
        thanos:
          image: quay.io/thanos/thanos:v0.28.1
          # renovate: datasource=docker depName=quay.io/thanos/thanos
          version: "v0.28.1"
          objectStorageConfig:
            name: thanos-objstore-secret
            key: objstore.yml
        resources:
          requests:
            # cpu: 50m
            memory: 3000Mi
          limits:
            memory: 7000Mi
        additionalScrapeConfigs:
          - job_name: kilns
            scrape_interval: 1m
            scrape_timeout: 30s
            honor_timestamps: true
            static_configs:
              - targets:
                  - "10.10.20.208"
          - job_name: extra-nodes
            scrape_interval: 1m
            scrape_timeout: 30s
            honor_timestamps: true
            static_configs:
              - targets:
                  - "192.168.1.22:9100"
                  - "10.10.20.208:9100"
          - job_name: zigbee2mqtt
            scrape_interval: 15s
            scrape_timeout: 10s
            honor_timestamps: true
            static_configs:
              - targets:
                  - "zigbee2mqtt-exporter"
#         - job_name: frr-exporter
#           scrape_interval: 1m
#           scrape_timeout: 10s
#           honor_timestamps: true
#           static_configs:
#             - targets:
#                 - "opnsense.${SECRET_PRIVATE_DOMAIN}:9342"
#         - job_name: node-exporter
#           scrape_interval: 1m
#           scrape_timeout: 10s
#           honor_timestamps: true
#           static_configs:
#             - targets:
#                 - "opnsense.${SECRET_PRIVATE_DOMAIN}:9100"
#                 - "expanse.${SECRET_PRIVATE_DOMAIN}:9100"
#         - job_name: pikvm
#           scrape_interval: 1m
#           scrape_timeout: 10s
#           metrics_path: /api/export/prometheus/metrics
#           basic_auth:
#             username: "${SECRET_PIKVM_USERNAME}"
#             password: "${SECRET_PIKVM_PASSWORD}"
#           honor_timestamps: true
#           static_configs:
#             - targets:
#                 - "pikvm.${SECRET_PRIVATE_DOMAIN}"
