---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name home-assistant
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
