---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kalooma-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-long-term
  resources:
    requests:
      storage: 10Gi
