---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tdarr-node
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    controller:
      type: daemonset

    image:
      repository: ghcr.io/haveagitgat/tdarr_node_acc
      tag: 2.16.01
    env:
      TZ: "${TZ}"
      PUID: "1000"
      PGID: "1000"
      serverIP: tdarr.media.svc.cluster.local
      serverPort: 8266
      ffmpegPath: "/usr/local/bin/ffmpeg"
      nodeName:
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    service:
      main:
        enabled: false
        ports:
          enabled: false
          http:
            port: 8265
    persistence:
      media:
        enabled: true
        type: nfs
        server: "192.168.1.22"
        path: /volume1/Media
        mountPath: /media
      cache:
        enabled: true
        type: nfs
        server: "192.168.1.22"
        path: /volume1/Media/cache
        mountPath: /cache
    resources:
      requests:
        cpu: 14m
        memory: 500Mi
        # limits:
        # gpu.intel.com/i915: "1"
    nodeSelector:
      tdarr: "true"
      intel.feature.node.kubernetes.io/gpu: "true"
