---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt-exporter
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/kpetrem/mqtt-exporter
      tag: latest@sha256:e5b5a02fba296635d7c151f5c155f798e77ca2e2909992d458f9a492fbb2e02c
    env:
      LOG_LEVEL: DEBUG
      LOG_MQTT_MESSAGE: "True"
      MQTT_ADDRESS: mosquitto
      MQTT_TOPIC: "zigbee2mqtt/#"
      MQTT_V5_PROTOCOL: "True"
      MQTT_USERNAME: "${MOSQUITTO_USER}"
      MQTT_PASSWORD: "${MOSQUITTO_PASS}"
      PROMETHEUS_PORT: &port 80
      PROMETHEUS_PREFIX: zigbee2mqtt_
      ZIGBEE2MQTT_AVAILABILITY: "True"
    service:
      main:
        ports:
          http:
            port: *port
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 200Mi
    nodeSelector:
      beta.kubernetes.io/arch: amd64
