---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - scripts
  - radarr
  - sonarr
  - sabnzbd
  - qbittorrent
  - tautulli
  - jackett
  - ombi  # FIXME - not working likely due to using the linuxserver image
  - flaresolverr
  - overseerr
