---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - scripts
  - radarr
  - sonarr
  - bazarr
  - sabnzbd
  - qbittorrent
  - tautulli
  - jackett
  - flaresolverr
  - overseerr
  - kapowarr
  #- tdarr
