apiVersion: v1
data:
    password: ENC[AES256_GCM,data:BbHa+erD95iP+81W,iv:sRX01wdZxy5WcC16InkKjYKyMFCgC6yQuMZ1y6BHuF8=,tag:TuADdXU5Ee1WOWOG/Zw2mQ==,type:str]
    user: ENC[AES256_GCM,data:m2XbN0mlN5c=,iv:EsieQo7tCI0EaVL2EwfQgk/mBiUO3EiurZt8/4DL0ws=,tag:t0ZmsrTUTb3/RQZCMNcFig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: media
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcHl6ZVNma05RNzdza0s3
            eXkvUlJPRFdaNDBTUlU3WnI5NGcxekdQYUhBCjRtZ0xPczhlSkUyanVTcG56VVU2
            Ukg2VzB4YzJmY2gwc3FEOW0xOVptRmcKLS0tIEY3TmpLUlcxZ0VJdjBjVitsdlZB
            ejdtb2tKTGZYNDFQV2xySWh3M0hlaWcKAYIWoI1s7NT+TY7wPt5nIUff3p2sZmg/
            GTE7x/p4Lxk2zk9GOfUACeJc3TpA1xBIJ6jXFOAmqlUj2uTTtKXtsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-01T14:33:06Z"
    mac: ENC[AES256_GCM,data:QMvqxLxBUEqVTA+WRCluLT6wKTvJke3XbYeL94Dox7SaVYpsFC7zT47wMXVkvCRqpPp5spn5sVfELAJnbTuZ5kDXoXqhEnMYkYD13Xe3xCEm9jMVCLQHDvpwu/AdSzNrOq3KzKYGSKtb29w3zTRNSUTJ3JRzaJ7fWPQ5gAhhvDo=,iv:YKNTHpRXggkY5lCwNxTNzgTJxFCoE1G4TREfbyxy5gE=,tag:dvhuWGCp8y0HYi0SXGzTZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
