---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: owntracks
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: owntracks
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: albatrossflavour
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  values:
    image:
      repository: owntracks/recorder


    env:
      TZ: "${TZ}"
      OTR_HOST: "${SVC_MOSQUITTO_ADDR}"
      OTR_USER: "${MOSQUITTO_USER}"
      OTR_PASS: "${MOSQUITTO_PASS}"
      SERVER_HOST: owntracks
      SERVER_PORT: "8083"

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      enabled: true
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
          nginx.ingress.kubernetes.io/satisfy: "any"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
        hosts:
          - host: &host "owntracks.lab.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: owntracks-config

    podAnnotations:
      backup.velero.io/backup-volumes: config

    resources:
      requests:
        cpu: 15m
        memory: 64M
