---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config
  namespace: default
  labels:
    app.kubernetes.io/name: &name mosquitto
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: default
  labels:
    app.kubernetes.io/name: &name mosquitto
    app.kubernetes.io/instance: *name
    policy.home.arpa/snapshot: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
