---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-config
  namespace: default
  labels:
    app.kubernetes.io/name: &name scrypted
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-block-long-term
