# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: default
stringData:
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:L+dCoMnWU22g0zvAPSMdLM9nqFAtZ1HBlDzgpJnU,iv:E6s5Ix0U26pAFDs3bXtb+BI7M0qpCimc9xuhln5BKIk=,tag:DGBp+VINiBPjb6Q24Mcpcg==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:QKEYsdXvQ27eeUWfc35KuzHkoMT0XkZrOfSUloeO,iv:40Q3kPEPqJPhZdllMwbRP6vz45VKVXvrO20MNYVpzbE=,tag:trxb7fdUR8v6UfHzKtDVaA==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:wp27Tmch7xA2FXep2PCbAV4AE+kkHZL/DufAIORXDto=,iv:/rRbR6eBf1QGmv7ozx3rGonb1qR/dbPHvc6VeCV0FZU=,tag:RgLBKrtrGLGBbejiEa/biQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjqyhkry5v2y5javn6l3f2pe2ezf3nvnp09unyevw9gl9pl5ddlsqdwkm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YWVvejlGWnNmZWs5SjBw
            OTZHOEVyUm1DV1BmanN0MCttNzh5SmdVUmxNClNiMEZlRE5WVm5ZY00zamNMbXMx
            R1F0NTVqNjc4VWEyZWtNbExDT2lNTEUKLS0tIEJnc0FOT2Y1MWs1NWRxV1AxdnlP
            ajVjUThEVDNwN1dqZ0lJTGt6YU5mSVUK9okMND98K8jEjKRlD1kAItkRtcWwr/iU
            a18V4YwhkyAi6auLRXnuprcP5K0muHY0RUkr7fmFMLlMqTvCXtzYyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-25T09:38:25Z"
    mac: ENC[AES256_GCM,data:Uyzzh7+4LdikuQOhaB+LtLeO0wOHkSzcc7sfjYgGfHMc9oqV0mSC4ybaUQZFoNXcrRET2WCbMtkK9LrtGJWpEcCfR3Sr3H1juVN4l7h3ibbBYhvoKo36se4NzOgWmnuY8rBw0AyS47qPbYY/zfQEDlRssFJ8n9AWgNn4zJKtyBY=,iv:JnElvXGf9p3LzxIcRTy7NIrl3reNeJuYtuH/8yVC1W8=,tag:TI0Bcvo+PyPhyUHPb9P3GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
