---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.9.9
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
  values:
    monitoring:
      enabled: false # FIX
      createPrometheusRules: false # FIX
    ingress:
      dashboard:
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "video-input-antenna"
          hajimari.io/instance: "internal"
          hajimari.io/group: "Cluster Ops"
        host:
          name: &host "rook.lab.${SECRET_DOMAIN}"
          path: "/"
        tls:
          - hosts:
              - *host
            secretName: "root-dashboard-tls"
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
    cephClusterSpec:
      network:
        provider: host
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: k8s-0
            devices:
              - name: "/dev/disk/by-id/scsi-SSamsung_Portable_SSD_T5_DF2238654321"
          - name: k8s-1
            devices:
              - name: "/dev/disk/by-id/scsi-SSamsung_Portable_SSD_T5_E29F48654321"
          - name: k8s-2
            devices:
              - name: "/dev/disk/by-id/scsi-SSamsung_Portable_SSD_T5_F2BB28654321"
      resources:
        mgr:
          limits:
            memory: "1Gi"
          requests:
            cpu: "150m"
            memory: "256Mi"
        mon:
          limits:
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "250Mi"
        osd:
          limits:
            memory: "1Gi"
          requests:
            cpu: "300m"
            memory: "500Mi"
        prepareosd:
          limits:
            memory: "200Mi"
          requests:
            cpu: "150m"
            memory: "25Mi"
        mgr-sidecar:
          limits:
            memory: "50Mi"
          requests:
            cpu: "50m"
            memory: "20Mi"
        crashcollector:
          limits:
            memory: "30Mi"
          requests:
            cpu: "50m"
            memory: "30Mi"
        logcollector:
          limits:
            memory: "250Mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
        cleanup:
          limits:
            memory: "250Mi"
          requests:
            cpu: "150m"
            memory: "50Mi"
#   cephBlockPoolsVolumeSnapshotClass:
#     enabled: true
#     name: csi-rbdplugin-snapclass
#     annotations:
#       velero.io/csi-volumesnapshot-class: "true"
#
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
              name: data0
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: 300m
                memory: 1Gi
              limits:
                memory: 500Mi
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          pool: data0
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              requests:
                cpu: 300m
                memory: 500Mi
              limits:
                memory: 500Mi
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          parameters:
            region: us-east-1
